#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const GENERATOR = path.join(
  ROOT,
  'scripts',
  'generate_index_pages.js'
);
const SITE_RESOURCES_PATH = path.join(
  ROOT,
  'assets',
  'js',
  'Config',
  'SiteResources.js'
);

const GENERATED_FILE_SIGNATURE =
  'AUTO-GENERATED by scripts/generate_index_pages.js';

const PAGE_HEADINGS = Object.freeze([
  {
    path: 'assets/js/Functions/about/About.js',
    className: 'about-heading'
  },
  {
    path: 'assets/js/Content/EN/schedule/schedule_EN.js',
    className: 'schedule-heading'
  },
  {
    path: 'assets/js/Functions/social/SocialShell.js',
    className: 'social-heading'
  },
  {
    path: 'assets/js/Functions/life/Life.js',
    className: 'life-heading'
  }
]);

function countOccurrences(text, pattern) {
  return Array.from(
    String(text || '').matchAll(pattern)
  ).length;
}

function loadSiteResources() {
  const code = fs.readFileSync(
    SITE_RESOURCES_PATH,
    'utf8'
  );

  const sandbox = {
    window: {
      SiteFonts: {
        externalStyles: []
      }
    }
  };

  vm.createContext(sandbox);
  vm.runInContext(code, sandbox, {
    filename:
      'assets/js/Config/SiteResources.js'
  });

  return sandbox.window.SiteResources;
}

function getGeneratedPaths() {
  return execFileSync(
    process.execPath,
    [GENERATOR, '--paths'],
    {
      cwd: ROOT,
      encoding: 'utf8'
    }
  )
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

function extractAlternates(html) {
  const pattern =
    /<link rel="alternate" data-site-language="([^"]+)" hreflang="([^"]+)" href="([^"]+)" \/>/g;

  return Array.from(
    html.matchAll(pattern),
    (match) => ({
      language: match[1],
      hreflang: match[2],
      href: match[3]
    })
  );
}

function getRouteParts(outputPath) {
  return outputPath === 'index.html'
    ? []
    : outputPath
        .replace(/\/index\.html$/, '')
        .split('/');
}

function collapseDefaultSubroute(
  logicalParts,
  defaultsByRoute
) {
  if (
    logicalParts.length === 2 &&
    defaultsByRoute[logicalParts[0]] ===
      logicalParts[1]
  ) {
    return logicalParts.slice(0, 1);
  }

  return logicalParts.slice();
}

function assertPageHeadingContracts(errors) {
  PAGE_HEADINGS.forEach((entry) => {
    const source = fs.readFileSync(
      path.join(ROOT, entry.path),
      'utf8'
    );

    const escapedClassName = entry.className
      .replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

    const openingPattern = new RegExp(
      `<h1\\b[\\s\\S]{0,180}?class=["'][^"']*\\b${escapedClassName}\\b[^"']*["']`,
      'i'
    );

    if (!openingPattern.test(source)) {
      errors.push(
        `${entry.path}: ${entry.className} must be rendered as an h1.`
      );
    }
  });
}

function main() {
  const resources = loadSiteResources();
  const localization = resources.localization;
  const languages = localization.languages;
  const defaultLanguage =
    localization.defaultLanguage;
  const canonicalOrigin =
    resources.site.canonicalOrigin.replace(/\/+$/, '');

  const defaultsByRoute = {};

  localization.localizedPages.forEach((pageKey) => {
    const page = resources.pages[pageKey];

    if (page.defaultSubroute) {
      defaultsByRoute[page.route] =
        page.defaultSubroute;
    }
  });

  const generatedPaths = getGeneratedPaths();
  const errors = [];

  generatedPaths.forEach((outputPath) => {
    const absolutePath = path.join(
      ROOT,
      outputPath
    );

    if (!fs.existsSync(absolutePath)) {
      errors.push(`${outputPath}: file is missing.`);
      return;
    }

    const html = fs.readFileSync(
      absolutePath,
      'utf8'
    );

    if (
      countOccurrences(
        html,
        new RegExp(GENERATED_FILE_SIGNATURE, 'g')
      ) !== 1
    ) {
      errors.push(
        `${outputPath}: expected one generator ownership signature.`
      );
    }

    if (/\{\{[A-Z0-9_]+\}\}/.test(html)) {
      errors.push(
        `${outputPath}: contains an unresolved template placeholder.`
      );
    }

    if (
      countOccurrences(
        html,
        /<main\b[^>]*id="site-main"[^>]*>/g
      ) !== 1 ||
      countOccurrences(html, /<\/main>/g) !== 1
    ) {
      errors.push(
        `${outputPath}: expected one site-main landmark.`
      );
    }

    const titleMatches = Array.from(
      html.matchAll(/<title>([^<]+)<\/title>/g)
    );

    if (
      titleMatches.length !== 1 ||
      !titleMatches[0][1].trim()
    ) {
      errors.push(
        `${outputPath}: expected one non-empty title.`
      );
    }

    const routeParts = getRouteParts(outputPath);
    const prefixed =
      routeParts.length > 0 &&
      languages.includes(routeParts[0]);
    const language = prefixed
      ? routeParts[0]
      : defaultLanguage;
    const logicalParts = prefixed
      ? routeParts.slice(1)
      : routeParts;
    const canonicalLogicalParts =
      collapseDefaultSubroute(
        logicalParts,
        defaultsByRoute
      );

    const expectedCanonicalPath =
      logicalParts.length === 0
        ? '/'
        : `/${language}/${canonicalLogicalParts.join('/')}/`;

    const canonicalMatches = Array.from(
      html.matchAll(
        /<link id="site-canonical" rel="canonical" href="([^"]+)" \/>/g
      )
    );

    if (
      canonicalMatches.length !== 1 ||
      canonicalMatches[0][1] !==
        canonicalOrigin + expectedCanonicalPath
    ) {
      errors.push(
        `${outputPath}: canonical URL is incorrect.`
      );
    }

    const expectedHtmlLanguage =
      localization.htmlLanguages[language];
    const htmlLanguageMatch =
      html.match(/<html lang="([^"]+)"/);

    if (
      !htmlLanguageMatch ||
      htmlLanguageMatch[1] !== expectedHtmlLanguage
    ) {
      errors.push(
        `${outputPath}: html lang is incorrect.`
      );
    }

    const depth = Math.max(
      0,
      outputPath.split('/').length - 1
    );
    const expectedBase = depth
      ? '../'.repeat(depth)
      : './';
    const baseMatch =
      html.match(/<base href="([^"]+)">/);

    if (
      !baseMatch ||
      baseMatch[1] !== expectedBase
    ) {
      errors.push(
        `${outputPath}: base href is incorrect.`
      );
    }

    const alternates = extractAlternates(html);

    if (logicalParts.length === 0) {
      if (alternates.length !== 0) {
        errors.push(
          `${outputPath}: neutral cover entry must not have language alternates.`
        );
      }
      return;
    }

    if (alternates.length !== languages.length) {
      errors.push(
        `${outputPath}: expected ${languages.length} language alternates.`
      );
      return;
    }

    languages.forEach((alternateLanguage) => {
      const alternate = alternates.find(
        (item) =>
          item.language === alternateLanguage
      );

      const expectedHref =
        canonicalOrigin +
        `/${alternateLanguage}/` +
        `${canonicalLogicalParts.join('/')}/`;

      if (
        !alternate ||
        alternate.hreflang !==
          localization.hreflangLanguages[
            alternateLanguage
          ] ||
        alternate.href !== expectedHref
      ) {
        errors.push(
          `${outputPath}: ${alternateLanguage} alternate is incorrect.`
        );
      }
    });
  });

  assertPageHeadingContracts(errors);

  if (errors.length) {
    console.error('\nIndex page contract errors:');
    errors.forEach((error) => {
      console.error(`- ${error}`);
    });
    process.exit(1);
  }

  console.log(
    `Index page contracts passed (${generatedPaths.length} entries).`
  );
}

main();
