#!/usr/bin/env node
'use strict';

const assert = require('assert/strict');
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const GENERATOR = path.join(
  ROOT,
  'scripts',
  'generate_index_pages.js'
);
const INDEX_CONFIG = require(
  './index_pages.config.js'
);
const TEMP_PARENT = path.join(ROOT, 'dist');
const TEMP_PREFIX = '.index-generator-check-';
const GENERATED_FILE_SIGNATURE =
  'AUTO-GENERATED by scripts/generate_index_pages.js';
const GENERATED_NOTICE =
  INDEX_CONFIG.generatedNotice;

function runGenerator(args, expectedStatus) {
  const result = spawnSync(
    process.execPath,
    [GENERATOR, ...args],
    {
      cwd: ROOT,
      encoding: 'utf8'
    }
  );

  assert.equal(
    result.status,
    expectedStatus,
    [
      `Generator exited with ${result.status}; expected ${expectedStatus}.`,
      result.stdout,
      result.stderr
    ].join('\n')
  );

  return result;
}

function main() {
  const tempParentExisted =
    fs.existsSync(TEMP_PARENT);

  fs.mkdirSync(TEMP_PARENT, {
    recursive: true
  });

  const tempRoot = fs.mkdtempSync(
    path.join(TEMP_PARENT, TEMP_PREFIX)
  );
  const outputRoot = path
    .relative(ROOT, tempRoot)
    .replace(/\\/g, '/');

  assert.equal(
    path.dirname(tempRoot),
    TEMP_PARENT,
    'Temporary generator output escaped its isolated parent.'
  );

  assert.ok(
    path.basename(tempRoot).startsWith(
      TEMP_PREFIX
    ),
    'Temporary generator output has an unexpected name.'
  );

  try {
    runGenerator(
      [`--output-root=${outputRoot}`],
      0
    );

    const orphanPath = path.join(
      tempRoot,
      'obsolete',
      'index.html'
    );
    const manualPath = path.join(
      tempRoot,
      'manual',
      'index.html'
    );
    const signatureMentionPath = path.join(
      tempRoot,
      'manual-signature-mention',
      'index.html'
    );

    fs.mkdirSync(path.dirname(orphanPath), {
      recursive: true
    });
    fs.mkdirSync(path.dirname(manualPath), {
      recursive: true
    });
    fs.mkdirSync(
      path.dirname(signatureMentionPath),
      {
        recursive: true
      }
    );

    fs.writeFileSync(
      orphanPath,
      `${GENERATED_NOTICE}\n`,
      'utf8'
    );
    fs.writeFileSync(
      manualPath,
      '<!DOCTYPE html><title>Manual</title>\n',
      'utf8'
    );
    fs.writeFileSync(
      signatureMentionPath,
      [
        '<!DOCTYPE html>',
        '<title>Manual signature mention</title>',
        `<!-- ${GENERATED_FILE_SIGNATURE} -->`,
        ''
      ].join('\n'),
      'utf8'
    );

    const checkResult = runGenerator(
      [
        `--output-root=${outputRoot}`,
        '--check'
      ],
      1
    );

    assert.match(
      checkResult.stdout,
      /orphan: obsolete\/index\.html/
    );
    assert.ok(fs.existsSync(orphanPath));
    assert.ok(fs.existsSync(manualPath));
    assert.ok(fs.existsSync(signatureMentionPath));

    const dryRunResult = runGenerator(
      [
        `--output-root=${outputRoot}`,
        '--dry-run'
      ],
      0
    );

    assert.match(
      dryRunResult.stdout,
      /would-delete: obsolete\/index\.html/
    );
    assert.ok(fs.existsSync(orphanPath));
    assert.ok(fs.existsSync(manualPath));
    assert.ok(fs.existsSync(signatureMentionPath));

    const generateResult = runGenerator(
      [`--output-root=${outputRoot}`],
      0
    );

    assert.match(
      generateResult.stdout,
      /deleted: obsolete\/index\.html/
    );
    assert.equal(fs.existsSync(orphanPath), false);
    assert.equal(
      fs.existsSync(path.dirname(orphanPath)),
      false
    );
    assert.ok(fs.existsSync(manualPath));
    assert.ok(fs.existsSync(signatureMentionPath));

    runGenerator(
      [
        `--output-root=${outputRoot}`,
        '--check'
      ],
      0
    );

    runGenerator(
      ['--output-root=../outside'],
      1
    );
    runGenerator(
      ['--output-root=.git/generated-check'],
      1
    );
    runGenerator(
      ['--output-root=scripts/generated-check'],
      1
    );

    console.log(
      'Index page generator ownership check passed.'
    );
  } finally {
    if (
      path.dirname(tempRoot) === TEMP_PARENT &&
      path.basename(tempRoot).startsWith(
        TEMP_PREFIX
      )
    ) {
      fs.rmSync(tempRoot, {
        recursive: true,
        force: true
      });
    }

    if (
      !tempParentExisted &&
      fs.existsSync(TEMP_PARENT) &&
      fs.readdirSync(TEMP_PARENT).length === 0
    ) {
      fs.rmdirSync(TEMP_PARENT);
    }
  }
}

main();
