'use strict';

module.exports = {
  title: 'Joker Chen',

  templatePath:
    'scripts/templates/index.template.html',

  siteResourcesPath:
    'assets/js/Config/SiteResources.js',

  preCoverLoadingStylePath:
    'assets/css/SitePreCoverLoading.css',

  preCoverLoadingScriptPath:
    'assets/js/Functions/general/SitePreCoverLoading.js',

  generatedNotice:
    '<!-- AUTO-GENERATED by scripts/generate_index_pages.js. Edit scripts/templates/index.template.html instead. -->',

  /*
    无前缀入口是正式的默认语言入口，不是兼容性残留。

    generate_index_pages.js 会自动读取
    SiteResources.localization.localizedPages，并为其中每个主模块生成：
    1. 无前缀的正式默认语言入口（例如 about/）
    2. 英文入口（例如 en/about/）
    3. 中文入口（例如 zh/about/）

    因此以后新增可翻译的主模块时，只要把页面配置加入
    SiteResources.pages 和 localization.localizedPages，
    不需要在这里重复登记主模块路径。

    这里只单独维护不需要语言前缀的中立入口。
  */
  neutralEntries: [
    {
      route: '',
      routeEntry: false,
      preCoverLoading: true
    }
  ],

  /*
    各可翻译主模块的正式副模块统一按页面 key 登记。

    generate_index_pages.js 会按照 SiteResources.localization
    自动组合页面 route 与副模块路径，并为每个逻辑路由生成
    无前缀、英文、中文三种正式入口。

    以后新增副模块时，只需在对应页面 key 的数组中加入
    相对于主模块的路径；无需重复书写 about、schedule 等前缀。
  */
  pageSubroutes: {
    resume: [
      'profile',
      'archive'
    ],
    schedule: [
      'calendar',
      'timetable',
      'my_timetable',
      'ustc_timetable'
    ],
    social: [
      'constellation',
      'identity',
      'footprints',
      'anime'
    ],
    life: [
      'activities_moments',
      'meditations'
    ]
  },

  /*
    Life 活动详情页从
    SiteResources.activitiesMoments.dates 自动读取。

    例如 dates 中有 2026_03_20，就会生成：
    life/activities_moments/2026_03_20/index.html
  */
  activityMomentDetailEntries: {
    enabled: true,
    sitePage: 'life',
    baseSubroute:
      'activities_moments'
  }
};
